<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyMedia.AppLayer\MyMedia.AppLayer.csproj" />
    <ProjectReference Include="..\MyMedia.Infrastructure\MyMedia.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\Pages\" />
    <Folder Include="Views\Pages\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
  </ItemGroup>

</Project>
